SSCS-10274 Store Hearing POST and GET Response to CCD
hmcts/sscs-hearings-api pull request #106
Opened 2022-04-25 15:26 UTC by TeaWithLucas

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/SSCS-10274

### Change description ###

- [x] Add State and Description and event for different Events for case History
- [x] Updated Hearing Response to long and int
- [x] Added updateHearingResponse method
- [x] Updated method updateCaseDetails to the more appropriate updateCaseData

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-04-25 15:48 UTC, suetlaiHMCTS approved these changes

2022-04-25 22:22 UTC, wmarshid commented on src/main/java/uk/gov/hmcts/reform/sscs/service/CcdCaseService.java
> +            throw new GetCaseException(String.format("Invalid case id format for %s",caseId),e);
Minor: formatting

2022-04-25 22:22 UTC, wmarshid commented on src/main/java/uk/gov/hmcts/reform/sscs/service/HearingsService.java
> +    public HearingsService(HmcHearingApi hmcHearingApi, CcdCaseService ccdCaseService, IdamService idamService) {
Minor: can use lombok for this

2022-04-25 22:22 UTC, wmarshid commented on src/main/java/uk/gov/hmcts/reform/sscs/service/HearingsService.java
> +        // TODO implement mapping for the event when a party has been notified, might not be needed
Is there a jira for this?

2022-04-25 22:22 UTC, wmarshid commented on src/test/java/uk/gov/hmcts/reform/sscs/service/HearingsServiceTest.java
> +        assertThat(wrapper.getCaseData().getEvents().get(0).getValue().getType()).isNotEmpty();
Optional: This would look a bit nicer if we use a variable for `wrapper.getCaseData().getEvents().get(0).getValue()`

2022-04-26 10:36 UTC, wmarshid requested changes

2022-04-26 10:36 UTC, wmarshid commented on src/main/java/uk/gov/hmcts/reform/sscs/service/HearingsService.java
> +@AllArgsConstructor
should be required args constructor

2022-04-26 10:36 UTC, wmarshid commented on src/main/java/uk/gov/hmcts/reform/sscs/service/HearingsService.java
> +        ccdCaseService.updateCaseData(wrapper.getCaseData(), event.getEventType(), event.getSummary(), event.getDescription());
Optional: would be nice to newline these parameters

2022-04-26 10:36 UTC, wmarshid commented on src/test/java/uk/gov/hmcts/reform/sscs/service/HearingsServiceTest.java
> +        EventDetails eventDetails = wrapper.getCaseData().getEvents().get(0).getValue();
Nice 👌

2022-04-26 10:36 UTC, wmarshid commented on src/test/java/uk/gov/hmcts/reform/sscs/helper/service/HearingsServiceHelperTest.java
> +        assertThat(wrapper.getCaseData().getEvents().get(0).getValue().getType()).isEqualTo(event.getEventType().getType());
Minor: Can we extract the eventValue to a variable for these tests as well?

2022-04-26 10:56 UTC, wmarshid requested changes

2022-04-26 10:56 UTC, wmarshid commented on src/main/java/uk/gov/hmcts/reform/sscs/service/HearingsService.java
>      public void processHearingRequest(HearingWrapper wrapper) throws UnhandleableHearingStateException {
Why don't we just call createWrapper in here? - don't think we need a separate method for this, harder to follow as well.

2022-04-26 11:31 UTC, dattipoeHMCTS approved these changes

2022-04-26 11:43 UTC, wmarshid approved these changes

2022-04-26 11:43 UTC, wmarshid commented on src/test/java/uk/gov/hmcts/reform/sscs/service/HearingsServiceTest.java
> +        given(idamService.getIdamTokens()).willReturn(IdamTokens.builder().idamOauth2Token(IDAM_OAUTH2_TOKEN).serviceAuthorization(SERVICE_AUTHORIZATION).build());
optional: can we new line builder methods for readability please

2022-04-26 13:24 UTC, wmarshid approved these changes

2022-04-26 13:49 UTC, dattipoeHMCTS approved these changes

2022-04-26 13:50 UTC, merged