SSCS-10294 Support for adjournment feature flag
hmcts/sscs-hearings-api pull request #368
Opened 2022-09-29 14:58 UTC by mcareyma

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/SSCS-10294

### Change description ###
Added support for adjournment feature flag, so that old code is run without the flag and the new code
only runs with the flag, and the tests test both.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-10-14 09:14 UTC, DGordonV1 requested changes

2022-10-14 09:14 UTC, DGordonV1 commented on src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDurationMapping.java
> +        return null;
No change, just wondering if returning null has any undesired impact here? I note we're already returning null in other methods.

Also, any reason to remove if/else if for multiple if statements? I'm not fussed on which is being used when returning within them, as you're not using additional overhead for the other ifs when a condition is met, so all good, just minor comment really.

2022-10-14 09:14 UTC, DGordonV1 commented on src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDurationMappingTest.java
> +        }
Repeated three times.

2022-10-14 09:23 UTC, amoslv1 commented on src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDurationMappingTest.java
> +        }
done

2022-10-14 12:24 UTC, DGordonV1 submitted a review, later dismissed

2022-10-18 08:39 UTC, dattipoeHMCTS commented on src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDurationMapping.java
> +    ) {
(m) weird formatting

2022-10-18 08:39 UTC, dattipoeHMCTS commented on src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDurationMapping.java
> +    private static Integer getHearingDurationAdjournmentOld(SscsCaseData caseData) {
What do 'old' and 'new' mean?

2022-10-19 13:05 UTC, closed without merging

2022-10-19 13:06 UTC, amoslv1 commented
Changes being made on another branch, so closing this PR