SSCS-10056 Create Hearing Domain Objects
hmcts/sscs-hearings-api pull request #40
Opened 2022-03-15 16:03 UTC by TeaWithLucas

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/SSCS-10056

### Change description ###

Update SSCS Commons Version

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-03-16 10:11 UTC, wmarshid approved these changes

2022-03-16 10:41 UTC, dattipoeHMCTS requested changes
Reminder about version

2022-03-17 18:01 UTC, suvarnathekkoot submitted a review, later dismissed

2022-03-18 12:55 UTC, cj1993 submitted a review, later dismissed

2022-05-20 12:54 UTC, closed without merging