Adding HMC delete endpoint
hmcts/sscs-hearings-api pull request #47
Opened 2022-03-22 08:44 UTC by ThomasKKC

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/SSCS-10277

### Change description ###
Implement call to HMC Delete Endpoint

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2022-03-22 09:34 UTC, wmarshid approved these changes
I think this looks okay but would like someone more familiar with the pact tests to review.

2022-03-22 10:44 UTC, dattipoeHMCTS requested changes

2022-03-22 10:44 UTC, dattipoeHMCTS commented on src/contractTest/java/uk/gov/hmcts/reform/sscs/consumer/HearingDeleteConsumerTest.java
> +            .body(toJsonString(generateInvalidHearingRequest())).headers(headers)
Won't an invalid delete request be one that's missing the cancellation reason?

2022-03-22 10:44 UTC, dattipoeHMCTS commented on src/contractTest/java/uk/gov/hmcts/reform/sscs/consumer/HearingDeleteConsumerTest.java
> +        assertTrue(hearingResponse.getHearingRequestId() > ZERO_LENGTH);
Can't you use not null and more concrete assertions?

2022-03-22 10:44 UTC, dattipoeHMCTS commented on src/main/java/uk/gov/hmcts/reform/sscs/service/HmcHearingApi.java
> +    @SuppressWarnings("PMD.UseObjectForClearerAPI")
It probably is worth creating a holder object for the request.

2022-03-23 11:20 UTC, wmarshid approved these changes

2022-03-23 11:43 UTC, merged