SSCS-10239: Functionality to send events to azure
hmcts/sscs-hearings-api pull request #52
Opened 2022-03-24 11:18 UTC by cj1993

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/SSCS-10239

### Change description ###

We want to be able to send Events to Azure AppInsights when we get a failed HMC response

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-03-24 17:15 UTC, dattipoeHMCTS requested changes

2022-03-24 17:15 UTC, dattipoeHMCTS commented on src/main/java/uk/gov/hmcts/reform/sscs/service/AppInsightsService.java
> +    private static String messageToJson(Message message) throws JsonProcessingException {
Sorry but I think we should add a couple of tests for this. I know JPEs shouldn't happen normally but I'm worried about a library bump causing issues silently and us losing these critical events.

2022-03-30 09:32 UTC, dattipoeHMCTS approved these changes

2022-03-30 09:58 UTC, ThomasKKC approved these changes
LGTM

2022-03-30 14:51 UTC, merged