SSCSCI-759: Handle other party hearingOptions NPE
hmcts/sscs-hearings-api pull request #615
Opened 2024-05-22 14:04 UTC by hashimalisolirius

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/SSCSCI-759

### Change description ###
Filter out other party if hearing options is not present

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2024-05-23 14:32 UTC, KatKovacs1 approved these changes

2024-05-23 14:39 UTC, sanjayparekh-hmcts requested changes

2024-05-23 14:39 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/ServiceHearingPartiesMapping.java
> +        partyDetails.partyChannel(partyChannel != null ? partyChannel.getHmcReference() : null);
I noticed this line does not have tests on the partyChannel = null condition
please see the build's sonar coverage, and see if you can incr the scrore

2024-05-23 14:42 UTC, NHAL22 submitted a review, later dismissed

2024-05-24 11:33 UTC, sanjayparekh-hmcts approved these changes

2024-05-24 12:33 UTC, NHAL22 submitted a review, later dismissed

2024-05-24 13:24 UTC, benouaer submitted a review, later dismissed

2024-06-25 11:18 UTC, nitinprabhuhmcts approved these changes

2024-06-25 11:33 UTC, merged