SSCS-10116
hmcts/sscs-hearings-api pull request #77
Opened 2022-04-01 07:49 UTC by suvarnathekkoot

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/SSCS-10116

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-04-01 10:20 UTC, cj1993 commented on src/main/java/uk/gov/hmcts/reform/sscs/helper/HearingsMapping.java
> +    private static SessionLookupService sessionLookupService;
This will need to be autowired through the constructor

2022-04-01 10:20 UTC, cj1993 commented on src/main/java/uk/gov/hmcts/reform/sscs/helper/HearingsMapping.java
> +    private HearingsMapping() {
Don't think this should be private

2022-04-01 10:27 UTC, cj1993 commented on src/main/java/uk/gov/hmcts/reform/sscs/helper/HearingsMapping.java
> +            if ("hours".equalsIgnoreCase(caseData.getAdjournCaseNextHearingListingDurationUnits())) {
Can you make "hours" a variable (like duration) or stick it in a constants file

2022-04-05 07:55 UTC, ss-evoco requested changes

2022-04-05 07:55 UTC, ss-evoco commented on src/main/java/uk/gov/hmcts/reform/sscs/service/HearingsService.java
> +
Feels like there should be more to this review / change

2022-04-05 13:05 UTC, gorkem-turan commented on src/main/java/uk/gov/hmcts/reform/sscs/helper/HearingsMapping.java
> +<<<<<<< HEAD
This one comes from merge conflict and is giving compilation error

2022-04-05 15:01 UTC, gorkem-turan commented on src/main/java/uk/gov/hmcts/reform/sscs/helper/HearingsDetailsMapping.java
> +import uk.gov.hmcts.reform.sscs.service.SessionLookupService;
SessionLookupService is not pushed so this line gives compilation error.

2022-04-06 09:49 UTC, dattipoeHMCTS commented on src/main/java/uk/gov/hmcts/reform/sscs/helper/HearingsDetailsMapping.java
> +
(Minor) extra space

2022-04-06 09:49 UTC, dattipoeHMCTS commented on src/main/java/uk/gov/hmcts/reform/sscs/helper/HearingsDetailsMapping.java
> +        // TODO Dependant on SSCS-10116 - Will be linked to Session Category Reference Data,
@suvarnathekkoot @TeaWithLucas Do we need a change here as well?

2022-04-06 09:49 UTC, dattipoeHMCTS commented on src/main/java/uk/gov/hmcts/reform/sscs/helper/HearingsDetailsMapping.java
> +        // TODO Dependant on SSCS-10116 - find out how to work this out and implement
@suvarnathekkoot @TeaWithLucas Do we need a change here as well?

2022-05-05 17:50 UTC, closed without merging