SSCS-10245 add three fields to HearingResponse.java and update a fiel…
hmcts/sscs-hearings-api pull request #88
Opened 2022-04-08 10:41 UTC by suetlaiHMCTS

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/SSCS-10360

### Change description ###

Adjust HearingResponse to match HMC Updates

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-04-08 10:46 UTC, gorkem-turan submitted a review, later dismissed

2022-04-11 16:13 UTC, dattipoeHMCTS approved these changes

2022-04-14 13:08 UTC, MohammedHMCTS approved these changes

2022-04-19 11:11 UTC, bensonlievoco approved these changes

2022-04-19 15:40 UTC, dattipoeHMCTS requested changes

2022-04-19 15:40 UTC, dattipoeHMCTS commented on config/owasp/suppressions.xml
> +    <notes><![CDATA[Awaiting new spring framework update]]></notes>
Could you please add which package it is? Like https://github.com/hmcts/sscs-hearings-api/blob/5dcf606d4cfa44e07c4f33c1677e3ae7fa93858f/config/owasp/suppressions.xml

2022-04-20 16:30 UTC, dattipoeHMCTS approved these changes

2022-04-21 08:39 UTC, MohammedHMCTS approved these changes

2022-04-21 09:12 UTC, merged